### ISSUE TITLE
Instructions for build and run

### ISSUE THREAD

**Issue by solderjs** [CleanCut/rusty_sword#1]
I'm assuming something like:

1. Install [Rust](https://rustup.rs)

2. Clone and Build "Rusty Sword"
    ```
    git clone git@github.com:CleanCut/rusty_sword.git
    pushd rusty_sword
    cargo build --release
    ```

3. Enjoy
    ```
    ./targets/release/rusty_sword --foo bar
    ```

**Comment by CleanCut** [comment]
I reorganized and beefed up the instructions on the readme so they will hopefully be both more noticeable and more useful. Thanks for the nudge. 😄
